# yaml-language-server: $schema=/data/work_projects/DCS-metadata/schemas/project.json
version: dcs-digitization-workflow-metadata@v1
project_information:
    creator: bdwheele
    create_date: '2024-07-23'
    completion_date: 
    contacts:
    -   name: 
        email: 
    notes: No Notes
descriptive_metadata:
    title: 
    identifiers:
        iucat_barcode: null
        iucat_catkey: null
        call_number: null
